//PAGE_TEXT list
export const FETCH_PAGE_TEXT = 'FETCH_PAGE_TEXT';
export const FETCH_PAGE_TEXT_SUCCESS = 'FETCH_PAGE_TEXT_SUCCESS';
export const FETCH_PAGE_TEXT_FAILURE = 'FETCH_PAGE_TEXT_FAILURE';
export const RESET_PAGE_TEXT = 'RESET_PAGE_TEXT';
