export const FETCH_CONTRACT = 'FETCH_CONTRACT'
export const FETCH_CONTRACT_SUCCESS = 'FETCH_CONTRACTS_SUCCESS'
export const FETCH_CONTRACT_FAILTURE = 'FETCH_CONTRACT_FAILTURE'

export const FETCH_CONTRACT_DATA = 'FETCH_CONTRACT_DATA'
export const FETCH_CONTRACT_DATA_SUCCESS = 'FETCH_CONTRACTS_DATA_SUCCESS'
export const FETCH_CONTRACT_DATA_FAILTURE = 'FETCH_CONTRACT_DATA_FAILTURE'

export const SEND_CONTRACT = 'SEND_CONTRACT'
export const SEND_CONTRACT_SUCCESS  = 'SEND_CONTRACT_SUCCESS '
export const SEND_CONTRACT_FAILTURE = 'SEND_CONTRACT_FAILTURE'
export const RESET_CONTRACT = 'RESET_CONTRACT'

export const SIGN_CONTRACT = 'SIGN_CONTRACT'
export const SIGN_CONTRACT_SUCCESS  = 'SIGN_CONTRACT_SUCCESS '
export const SIGN_CONTRACT_FAILURE = 'SIGN_CONTRACT_FAILURE'

export const FETCH_ORGANIZATIONS_BY_INN = 'FETCH_ORGANIZATIONS_BY_INN'
export const FETCH_ORGANIZATIONS_BY_INN_SUCCESS  = 'FETCH_ORGANIZATIONS_BY_INN_SUCCESS '
export const FETCH_ORGANIZATIONS_BY_INN_FAILTURE = 'FETCH_ORGANIZATIONS_BY_INN_FAILTURE'

export const RESET_SUGGESTIONS = 'RESET_SUGGESTIONS'