//Fetch ORDERS
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

//Fetch Form Results
export const FETCH_FORM_RESULTS = 'FETCH_FORM_RESULTS'
export const FETCH_FORM_RESULTS_SUCCESS = 'FETCH_FORM_RESULTS_SUCCESS'
export const FETCH_FORM_RESULTS_FAILURE = 'FETCH_FORM_RESULTS_FAILURE'

//Fetch Order Status List
export const FETCH_ORDER_STATUS_LIST = 'FETCH_ORDER_STATUS_LIST'
export const FETCH_ORDER_STATUS_LIST_SUCCESS = 'FETCH_ORDER_STATUS_LIST_SUCCESS'
export const FETCH_ORDER_STATUS_LIST_FAILURE = 'FETCH_ORDER_STATUS_LIST_FAILURE'

//Order Status
export const SET_ORDER_STATUS = 'SET_ORDER_STATUS';
export const SET_ORDER_STATUS_SUCCESS = 'SET_ORDER_STATUS_SUCCESS';
export const SET_ORDER_STATUS_FAILURE = 'SET_ORDER_STATUS_FAILURE';

//Order list clean
export const CLEAN_ORDER = 'CLEAN_ORDER';

//Update object status
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';

//Reset FILTER

export const RESET_FILTER = 'RESET_FILTER';

export const NOTIFY = 'NOTIFY';