export const FETCH_SUBORDINATE = 'FETCH_SUBORDINATE'
export const FETCH_SUBORDINATE_SUCCESS = 'FETCH_SUBORDINATE_SUCCESS'
export const FETCH_SUBORDINATE_FAILURE = 'FETCH_SUBORDINATE_FAILURE'

export const UPDATE_SUBORDINATE = 'UPDATE_SUBORDINATE'
export const UPDATE_SUBORDINATE_SUCCESS = 'UPDATE_SUBORDINATE_SUCCESS'
export const UPDATE_SUBORDINATE_FAILURE = 'UPDATE_SUBORDINATE_FAILURE'
//Validate
export const VALIDATE_SUBORDINATE_FIELDS = 'VALIDATE_SUBORDINATE_FIELDS';
export const VALIDATE_SUBORDINATE_FIELDS_SUCCESS = 'VALIDATE_USER_SUBORDINATE_SUCCESS';
export const VALIDATE_SUBORDINATE_FIELDS_FAILURE = 'VALIDATE_USER_SUBORDINATE_FAILURE';
export const RESET_VALIDATE_SUBORDINATE_FIELDS = 'RESET_VALIDATE_SUBORDINATE_FIELDS';