//Objs list
export const FETCH_INVOICES = 'FETCH_INVOICES';
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_FAILURE = 'FETCH_INVOICES_FAILURE';
export const RESET_INVOICES = 'RESET_INVOICES';

export const FETCH_INVOICE_LINK = 'FETCH_INVOICE_LINK'
export const FETCH_INVOICE_LINK_SUCCESS = 'FETCH_INVOICE_LINK_SUCCESS'
export const FETCH_INVOICE_LINK_FAILURE = 'FETCH_INVOICE_LINK_FAILURE'
