//Objs list
export const FETCH_OBJECTS = 'FETCH_OBJECTS';
export const FETCH_OBJECTS_SUCCESS = 'FETCH_OBJECTS_SUCCESS';
export const FETCH_OBJECTS_FAILURE = 'FETCH_OBJECTS_FAILURE';
export const RESET_OBJECTS = 'RESET_OBJECTS';
