//Update OBJECT
export const UPDATE_OBJECT_PROPS_GROUP = 'UPDATE_OBJECT_PROPS_GROUP+GROUP';
export const UPDATE_OBJECT_PROPS_GROUP_SUCCESS = 'UPDATE_OBJECT_PROPS_GROUP_SUCCESS';
export const UPDATE_OBJECT_PROPS_GROUP_FAILURE = 'UPDATE_OBJECT_PROPS_GROUP_FAILURE';
export const VALIDATE_UPDATING_OBJECT_PROPS_GROUP_FIELDS_FAILURE = 'VALIDATE_UPDATING_OBJECT_PROPS_GROUP_FIELDS_FAILURE'
