//Fetch OBJECT
export const FETCH_OBJECT = 'FETCH_OBJECT';
export const FETCH_OBJECT_SUCCESS = 'FETCH_OBJECT_SUCCESS';
export const FETCH_OBJECT_FAILURE = 'FETCH_OBJECT_FAILURE';
export const RESET_ACTIVE_OBJECT = 'RESET_ACTIVE_OBJECT';

//Update OBJECT
export const UPDATE_OBJECT = 'UPDATE_OBJECT';
export const UPDATE_OBJECT_SUCCESS = 'UPDATE_OBJECT_SUCCESS';
export const UPDATE_OBJECT_FAILURE = 'UPDATE_OBJECT_FAILURE';
export const VALIDATE_UPDATING_OBJECT_FIELDS_FAILURE = 'VALIDATE_UPDATING_OBJECT_FIELDS_FAILURE'

//Update PHOTOS
export const UPLOAD_OBJECT_PHOTOS = 'UPLOAD_OBJECT_PHOTOS';
export const UPLOAD_OBJECT_PHOTOS_SUCCESS = 'UPLOAD_OBJECT_PHOTOS_SUCCESS';
export const UPLOAD_OBJECT_PHOTOS_FAILURE = 'UPLOAD_OBJECT_PHOTOS_FAILURE';
//Delete PHOTO
export const DELETE_OBJECT_PHOTO = 'DELETE_OBJECT_PHOTO';
export const DELETE_OBJECT_PHOTO_SUCCESS = 'DELETE_OBJECT_PHOTO_SUCCESS';
export const DELETE_OBJECT_PHOTO_FAILURE = 'DELETE_OBJECT_PHOTO_FAILURE';

//Fetch COUNTRIES
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';

//Fetch CITYIES
export const FETCH_CITIES = 'FETCH_CITIES';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE';

//Fetch OBJECT
export const GEOCODER = 'GEOCODER';
export const GEOCODER_SUCCESS = 'GEOCODER_SUCCESS';
export const GEOCODER_FAILURE = 'GEOCODER_FAILURE';

export const FETCH_PAYMENT_TYPES = 'FETCH_PAYMENT_TYPES'
export const FETCH_PAYMENT_TYPES_SUCCESS = 'FETCH_PAYMENT_TYPES_SUCCESS'
export const FETCH_PAYMENT_TYPES_FAILURE = 'FETCH_PAYMENT_TYPES_FAILURE'

