//rooms list
export const FETCH_ROOMS = 'FETCH_ROOMS';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_FAILURE = 'FETCH_ROOMS_FAILURE';
export const RESET_ROOMS = 'RESET_ROOMS';

export const CREATE_ROOM = 'CREATE_ROOM'
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS'
export const CREATE_ROOM_FAILURE = 'CREATE_ROOM_FAILURE'

export const RESET_NEW_ROOM = 'RESET_NEW_ROOM'

export const FETCH_TYPES = 'FETCH_TYPES'
export const FETCH_TYPES_SUCCESS = 'FETCH_TYPES_SUCCESS'
export const FETCH_TYPES_FAILURE = 'FETCH_TYPES_FAILURE'

export const FETCH_ROOM = 'FETCH_ROOM';
export const FETCH_ROOM_SUCCESS = 'FETCH_ROOM_SUCCESS';
export const FETCH_ROOM_FAILURE = 'FETCH_ROOM_FAILURE';
export const RESET_ACTIVE_ROOM = 'RESET_ACTIVE_ROOM';

export const UPDATE_ROOM = 'UPDATE_ROOM'
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS'
export const UPDATE_ROOM_FAILURE = 'UPDATE_ROOM_FAILURE'

export const DELETE_ROOM = 'DELETE_ROOM'
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS'
export const DELETE_ROOM_FAILURE = 'DELETE_ROOM_FAILURE'
export const RESET_DELETED_ROOM = 'RESET_DELETED_ROOM'

export const UPLOAD_ROOM_PHOTOS = 'UPLOAD_ROOM_PHOTOS';
export const UPLOAD_ROOM_PHOTOS_SUCCESS = 'UPLOAD_ROOM_PHOTOS_SUCCESS';
export const UPLOAD_ROOM_PHOTOS_FAILURE = 'UPLOAD_ROOM_PHOTOS_FAILURE';
//Delete PHOTO
export const DELETE_ROOM_PHOTO = 'DELETE_ROOM_PHOTO';
export const DELETE_ROOM_PHOTO_SUCCESS = 'DELETE_ROOM_PHOTO_SUCCESS';
export const DELETE_ROOM_PHOTO_FAILURE = 'DELETE_ROOM_PHOTO_FAILURE';

export const UPDATE_ROOMS_CALENDAR = 'UPDATE_ROOMS_CALENDAR'
export const UPDATE_ROOMS_CALENDAR_SUCCESS = 'UPDATE_ROOMS_CALENDAR_SUCCESS'
export const UPDATE_ROOMS_CALENDAR_FAILURE = 'UPDATE_ROOMS_CALENDAR_FAILURE'

export const UPDATE_ROOMS_CALENDAR_BY_PERIOD = 'UPDATE_ROOMS_CALENDAR_BY_PERIOD'
export const UPDATE_ROOMS_CALENDAR_BY_PERIOD_SUCCESS = 'UPDATE_ROOMS_CALENDAR_BY_PERIOD_SUCCESS'
export const UPDATE_ROOMS_CALENDAR_BY_PERIOD_FAILURE = 'UPDATE_ROOMS_CALENDAR_BY_PERIOD_FAILURE'

export const CHANGE_ROOMS_CALENDAR_TYPE = 'CHANGE_ROOMS_CALENDAR_TYPE'
export const CHANGE_ROOMS_CALENDAR_TYPE_SUCCESS = 'CHANGE_ROOMS_CALENDAR_TYPE_SUCCESS'
export const CHANGE_ROOMS_CALENDAR_TYPE_FAILURE = 'CHANGE_ROOMS_CALENDAR_TYPE_FAILURE'
