//Create Object
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const CREATE_OBJECT = 'CREATE_OBJECT';
export const CREATE_OBJECT_SUCCESS = 'CREATE_OBJECT_SUCCESS';
export const CREATE_OBJECT_FAILURE = 'CREATE_OBJECT_FAILURE';